version: '3.8'
services:
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: yotter
      MYSQL_USER: yotter
      MYSQL_PASSWORD: changeme
    restart: unless-stopped
    volumes:
     - /var/lib/mysql
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "--silent"]
  yotter:
    image: yotter
    restart: unless-stopped
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      DATABASE_URL: mysql+pymysql://yotter:changeme@mariadb:3306/yotter
    depends_on:
      - mariadb
    ports:
      - "5000:5000"
    volumes:
     - /usr/src/app/migrations
     - ./yotter-config.json:/usr/src/app/yotter-config.json
